name: Package Project

# kiedy mam uruchomic automatyzacje
on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # pobierz kod
      - uses: actions/checkout@v3
      # moja aplikacja jest w Pythonie
      - name: Set up Python 3
        uses: actions/setup-python@v3
      # instalacja wymaganych bibliotek
      - name: Install deps
        run: make deps
      # testy!!!!!
      - name: Tests
        run: make test
    run-linters:
        name: Run linters
        runs-on: ubuntu-latest

        steps:
          - name: Check out Git repository
            uses: actions/checkout@v2

          # Install your linters here

           - name: Run linters
            uses: wearerequired/lint-action@v2
            with:
            # Enable your linters here